anchor_version = "0.24.2"

[programs.mainnet]
canonical_swap = "CSWAPqg5XDRcknL2CmDVtmBHX2KFEnaLZgHFCC89nhDk"

[programs.devnet]
canonical_swap = "CSWAPqg5XDRcknL2CmDVtmBHX2KFEnaLZgHFCC89nhDk"

[programs.localnet]
canonical_swap = "CSWAPqg5XDRcknL2CmDVtmBHX2KFEnaLZgHFCC89nhDk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
