anchor_version = "0.18.2"

[programs.mainnet]
canonical_swap = "CNSWAP9TsKjy3Ux1QxptQS2RFAiP5Eucf4odRHueNwzm"

[programs.localnet]
canonical_swap = "CNSWAP9TsKjy3Ux1QxptQS2RFAiP5Eucf4odRHueNwzm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
